### ISSUE TITLE
FEATURE REQUEST: Add Currency Conversion Utilities

### ISSUE THREAD

**Issue by adam-rocska** [Mordil/swift-currency#37]
The library concept is awesome and could lead to great stuff in the future.
It would be great to include some currency conversion utilities which could potentially allow us wild ass stuff, like : `let myCash = (USD(300) + EUR(150)) as HUF`

What do you think?

**Comment by Mordil** [comment]
Hi @adam-rocska thanks for the suggestion!

I've been thinking about currency exchanges since I started work on SwiftCurrency, and I'd love to see it done. However, exchanges rates change _by the second_ across the world, and the only way to correctly (legally, economically, mathematically) convert one currency into another is from a live currency service.

This could be done as another library product (e.g. `CurrencyExchange`) that SwiftCurrency would provide - but I think it might be better as a separate package so that `Currency` can be the baseline API which other packages can interop with. This is as similar approach to both [`SwiftMetrics`](https://github.com/apple/swift-metrics) and [`SwiftLog`](https://github.com/apple/swift-log).

I would expect such a library would provide a mechanism for connecting to any of the various free & paid exchange services such as [Open Exchange Rates](https://openexchangerates.org/) or [XE Currency Data](https://www.xe.com/xecurrencydata/).

I have wanted to start this myself, but I've been busy with other projects as well as my day job. If you or anyone else want to spearhead this - I'm willing to give a steering direction to move towards!

As such - this feature is out of scope for the `Currency` package.
